### ISSUE TITLE
How do we use this reporter in Mocha?

### ISSUE THREAD

**Issue by SashaBayan** [markotom/mocha-funnynyan-reporter#1]
How can we add this reporter as an option for Mocha's reporter key? It's not showing up with `mocha --reporters`, and trying `mocha --reporter FunnyNyan` gave an error:

> Warning: invalid reporter "FunnyNyan" Use --force to continue.

**Comment by markotom** [comment]
So sorry for the delay. Never you will get the name of `FunnyNyan` with `mocha --reporters`, just install this custom reporter into your project and run with the correct name:

``` bash
$ npm i mocha-funnynyan-reporter --save-dev
$ mocha --reporter mocha-funnynyan-reporter
```

:)
